name: 更新台湾节点订阅

on:
  schedule:
    - cron: "0 */1 * * *"  # 每6小时自动更新
  workflow_dispatch:  # 允许手动触发

jobs:
  update_subscription:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: 运行脚本筛选台湾节点
        run: |
          python filter_tw.py

      - name: 提交更新
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"
          git add taiwan.yaml
          git commit -m "更新台湾节点订阅" || echo "No changes to commit"
          git push
